### ISSUE TITLE
New Version doesnt detect some things that previous one did

### ISSUE THREAD

**Issue by darkhellsatan666** [Brandon-T/Coin-Blocker#1]
First of all, thanks for your great work, your extension has been a great security addition to my browsing experience, with some flaws y must say, but without becoming miner without consent after all.
Now, your axtension has been blocking an annoying miner script without problems, however, the new version is not doing his job properly and let some miner script execute.
Look this:
This page, http://skyback.ru/ at the begin, when page start loading code, and you stop the loading process and inspect (with firefox inspector) the page injects this script:

<script type="text/javascript" src="https://cloudcdn.gdn/js/DQ1HQYAUbcAVLQwBXdlXRxlY6YwO10UKKByM3sgI8cHEsg2SjcBLs4TXbczFuFwBmtQEeIBSmMyDChFUNYhG0ERIGQgMlcxUNtDbwgBNY8CB-8VUDk0N9c2SjwAPtRBPoYmAR8BEBcSGkQiEJYgVVlEGSJEUQxwa.js?trl=0.30"></script>

You can see this screenshot to make a better idea of the script execution context:

https://i.imgur.com/DVVApwv.jpg

When page is fully loaded this line dissappear, however, the code contained on this script is being executed and generate a cpu usage of 95%

Now, if you take a look to the script source code ( view-source:https://cloudcdn.gdn/js/DQ1HQYAUbcAVLQwBXdlXRxlY6YwO10UKKByM3sgI8cHEsg2SjcBLs4TXbczFuFwBmtQEeIBSmMyDChFUNYhG0ERIGQgMlcxUNtDbwgBNY8CB-8VUDk0N9c2SjwAPtRBPoYmAR8BEBcSGkQiEJYgVVlEGSJEUQxwa.js?trl=0. )

I'm not a programmer, but in the latest code lines you can clearly see this:

sessionStorage[_0x9bb2('0xe5')](_0x9bb2('0x1b9'),0x1);runMiner();}}else{runMiner();}if(document[_0x9bb2('0x1fb')]){var node=document[_0x9bb2('0x1fb')](_0x9bb2('0x1fc'));if(node&&node[_0x9bb2('0x1fd')]){node[_0x9bb2('0x1fd')]();}}

For me this is obviously a miner script, and i don't know what changes you did to the detection algorithm, but now this code is not being detected.

Please, take a look to this, thanks and merry christmas

**Comment by Brandon-T** [comment]
Fixed in Extensions for: Firefox v1.0.2 and Chrome v1.0.3.
Safari doesn't seem to have this issue.

The issue is caused by: https://stackoverflow.com/questions/47910732/browserextension-webrequest-onbeforerequest-return-promise

The workaround is the make the scanning/requests synchronous. It makes the scanning a little bit slower, but this is way better than getting CPU spike to 100%. Once the page loads, it's fine too :)

**Comment by darkhellsatan666** [comment]
Thanks a lot!!!, now it works properly :)
